apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-monitor
spec:
  selector:
    matchLabels:
      name: monitor
  template:
    metadata:
      labels:
        name: monitor
    spec:
      containers:
      - name: monitor-agent
        image: alpine
        command: ["sh", "-c", "while true; do sleep 3600; done"] # Simulating a background agent