apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-scaler
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-scaler
  template:
    metadata:
      labels:
        app: frontend-scaler
    spec:
      containers:
        - name: frontend-scaler
          image: frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://backend-service:5000"